services:
  - type: web
    name: kurt-dashboard
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: VPS_INSTALL_URL
        value: https://216.40.79.16:3005/install

      - key: VPS_STATUS_URL
        value: https://216.40.79.16:3005/status

      - key: VPS_SEND_CREDS_URL
        value: https://216.40.79.16:3005/send-creds
